### ISSUE TITLE
linux-5.10 support?

### ISSUE THREAD

**Issue by l4es** [STMicroelectronics/STMems_Linux_IIO_drivers#14]
Dear STMicroelectronics,

I would like to know if you would support Linux kernel version 5.10 and above as most of embedded systems are pumped up to those kernel versions ? 

We were successful to use your latest branch linux-4.19.y-gh into kernel 5.4.x. However, there's big jump from 5.4.x to 5.10.y and the drivers' code would need to be adapted I guess.

Thanks in advance and best regards,
Khang

**Comment by mariotesi** [comment]
shortly we will discontinue this Linux IIO Drivers repo in favor of the [new](https://github.com/STMicroelectronics/st-mems-android-linux-drivers-iio) one which we will keep updated with the most recent kernels
