### ISSUE TITLE
linux-5.15 support

### ISSUE THREAD

**Issue by MarkusDost** [STMicroelectronics/STMems_Linux_IIO_drivers#16]
Hello,

since NXP has released a BSP with LTS kernel 5.15 for their iMX chips I would like to know if there are plans for supporting this kernel version.

When compiling the driver for LIS2DW12/IIS2DLPC for linux-5.15 I got the following error:

st_lis2dw12_buffer.c:308:18: error: implicit declaration of function 'devm_iio_kfifo_allocate'; did you mean 'iio_kfifo_allocate'? [-Werror=implicit-function-declaration]

The function 'devm_iio_kfifo_allocate' was changed to a private function in kernel 5.13 and replaced by 'devm_iio_kfifo_buffer_setup' in header 'kfifo_buf.h'

Best regards,
Markus

**Comment by mariotesi** [comment]
We do not support kernel 5.15 on this repo, pls refer to the [new](https://github.com/STMicroelectronics/st-mems-android-linux-drivers-iio)
